--------------- comp_documentation ------------------    
drop table comp_documentation;
--------------- comp_catalog ------------------
drop table comp_catalog;
--------------- categories ------------------
drop table categories;
--------------- comp_categories ------------------
drop table comp_categories;
--------------- catalog ------------------
drop table catalog;
--------------- category_catalog ------------------
drop table category_catalog;
--------------- phase ------------------
drop table phase;
--------------- comp_versions ------------------
drop table comp_versions;
--------------- technology_types ------------------
drop table technology_types;
--------------- comp_technology ------------------
drop table comp_technology;
--------------- comp_version_dates ------------------    
drop table comp_version_dates;
--------------- client ------------------    
drop table client;
--------------- user_client ------------------    
drop table user_client;
--------------- comp_client ------------------    
drop table comp_client;
--------------- comp_user ------------------    
drop table comp_user;
--------------- comp_jive_category_xref ------------------    
drop table comp_jive_category_xref;
--------------- comp_link ------------------    
drop table comp_link;
--------------- doc_types ------------------    
drop table doc_types;

