<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<div class="logoArea">
    <a href="#"><img src="/images/TopCoder_logo.png" alt="TopCoder"/></a>
</div>

<div class="helpArea">
    <div class="caption">
        <div class="captionLeft">
            <div class="captionRight">
                <div class="captionInner">
                    <h2>TopCoder Direct Terms</h2>
                </div>
            </div>
        </div>
    </div>
    <!-- End .caption -->

    <p>
    <pre>These TopCoder Direct Terms ("Agreement") are an agreement between you and TopCoder, Inc. ("TopCoder," "we," "us," or "our"). You means either yourself personally, or the company on the behalf of whom you are requesting Competition Services (defined below). Each of you and TopCoder are a party to this Agreement and TopCoder and you are the parties. This Agreement governs your use of the TopCoder Direct service ("Service"). This Agreement is in addition to the Terms of Use applicable to the TopCoder website.
The Service allows customers to hold competitions for the development of graphics and design-related material. TopCoder makes no guarantee about the reliability, quality, performance, accuracy, or timeliness of the Service or the results obtained from the Service. You understand that any security mechanisms provided by the Service have inherent limitations and that you are responsible for determining whether the Service meets your needs.
You represent that you are at least 18 years old. Your use of the Service is conditioned on your acceptance without modification of all of the terms and conditions, rules, conditions, and notices on the TopCoder website, including without limitation this Agreement, as may be modified by TopCoder. TopCoder reserves the right, in its discretion, to change or modify all or any part of this Agreement at any time, effective immediately upon publish to the TopCoder website. The most current version of this Agreement can be viewed by clicking on the "Terms of Use" link on the TopCoder Direct web site. If at any time you do not agree to accept and abide by this Agreement, you should not access or use the Service.
PRIVACY
In order to operate and provide the Service, we collect certain information about you. We use and protect that information as described in the TopCoder Privacy Policy, available at: http://www.topcoder.com/tc?module=Static&d1=about&d2=privacy
1. SERVICES.
1.1 Custom Competitions. TopCoder will conduct online competitions for you among members of TopCoder's community as designed by you on the TopCoder web site and as approved and agreed to by TopCoder ("Competition Services"). TopCoder shall have the right, but not the obligation, to review all competition documents (e.g., specifications, contest rules and requirements, prizes, etc.) and may require that you make such changes as TopCoder deems necessary in TopCoder's sole discretion to maintain the integrity of the competitions and the platform. TopCoder reserves the right to terminate any online competition, for any reason or no reason, in its sole discretion, whether or not TopCoder has reviewed the competition documents.
1.2 Your Use of the Competition Services. In addition to the restrictions provided in the TopCoder Terms of Use, You agree that you will not:
Fail to pay for competitions initiated by you or for content used by you;
Manipulate the prize for a competition;
Circumvent or manipulate the fee structure, billing process or fees owed to TopCoder;
Transfer your account to another party without TopCoder's prior written consent;
Copy, modify, or transfer content from the Service or any information protected by copyright and/or trademark laws except as explicitly permitted under this Agreement;
Use any Third Party Content in the Service which is protected by copyright and/or trademark laws unless you are able to demonstrate the possession of the necessary rights and/or licenses to such content;
Take any action that imposes or may impose (in our sole discretion) an unreasonable or disproportionately large load on our infrastructure;
Interfere or attempt to interfere with the proper working of the Competition Services or any activity conducted on the web site;
Harvest or otherwise collect information about users without the consent of TopCoder and the users.
Engage or act in a dishonest or unfair manner, or in bad faith.
Modify, publish, transmit, transfer or sell, reproduce, create derivative works from, distribute, perform, display, reverse engineer or in any way exploit any of the content on the web site or as part of the Competition Services except as explicitly permitted under this Agreement.
1.3 Transfer of Deliverables. Upon payment in full of all outstanding invoices, all work product other than Third-Party Content and Licensed Content, developed in the course of Competition Services and Consulting Services and delivered to you under this Agreement ("Deliverables") shall be owned by you. TopCoder agrees to assign to you all of its right, title, and interest in and to such Deliverables, subject to payment of all fees.
1.4 Licensed Content. In the event you use or require content or software designated by TopCoder as owned or licensed by TopCoder ("Licensed Content"), whether from a TopCoder software component, widget, photo, or design catalog or otherwise, in any competition, such Licensed Content shall be licensed (and not assigned) to you in accordance with the terms of this Section 1.4. Subject to full payment of all amounts owed and this Agreement, TopCoder grants to you a non-exclusive, non-transferable license under TopCoder's copyrights in the Licensed Content to copy, modify, prepare derivative works, distribute, publicly perform and publicly display the Licensed Content; provided, however, that you may not may not sublicense, distribute or resell the Licensed Content to any third party separate from or for use other than as incorporated into the Deliverables. TopCoder retains all right, title and interest in and to the Licensed Content. Any use of the Licensed Content beyond the scope of the licenses expressly granted herein is prohibited. You shall retain all copyright notices and authorship credits for the Licensed Content in the Deliverable and associated documentation. Nothing in this Agreement shall be construed so as to prohibit TopCoder from reusing any Licensed Content, whether existing before or developed during or after Deliverables.
1.5 Third-Party Content. If you request that the Deliverables interface with, accompany, or include content or material not developed or licensed by TopCoder ("Third-Party Content"), any such Third-Party Content shall be subject to its own terms and conditions, and shall not be considered part of the Deliverables under this Agreement. You represent that you have all rights in the Third-Party Content specified or provided by you that are necessary to authorize its use in Competition Services and incorporation into the Deliverables. You agree to indemnify TopCoder for any breach of this indemnification.
2. DISCLAIMER OF WARRANTIES. To the extent permitted by law, the Deliverables and all TopCoder services are provided AS IS, WITH ALL FAULTS, and TOPCODER MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE, TITLE, OR NONINFRINGEMENT. No statement by TopCoder's personnel or otherwise shall be deemed to be a warranty by TopCoder for any purpose or to give rise to any liability on the part of TopCoder unless contained in this Agreement. The parties acknowledge and agree that the fees charged by TopCoder under this Agreement reflect the allocation of risks provided by the foregoing warranty, the limitations of liability, and other terms set forth in this Agreement, and any modification of the allocation of risks would affect the fees charged.
3. PAYMENT. Payment will be required upon execution of a request for Competition Services. In the event that payment does not go through (for example, if a credit card payment is rejected) TopCoder may charge interest on overdue amounts at the rate of 1.5% per month or the highest lawful rate, whichever is less. You agree to pay to TopCoder all costs of collection of overdue amounts incurred by TopCoder. You shall be responsible for all taxes under this Agreement, except those taxes based on TopCoder's income or payroll.
4. TERM AND TERMINATION. The Competition Services may be terminated by TopCoder at any time, and for any reason. Notwithstanding any termination of this Agreement, you shall remain obligated to pay all fees for competitions launched and services rendered prior to termination. Section 2 (Disclaimer of Warranties), Section 3 (Payment), Section 4 (Term and Termination), Section 5 (Limitation of Liability), Section 7 (Arbitration), Section 8 (Promotion), and Section 9 (General) of this Agreement shall survive any termination.
5. LIMITATION OF LIABILITY. NEITHER PARTY SHALL BE LIABLE TO THE OTHER, UNDER THIS AGREEMENT OR OTHERWISE FOR ANY CLAIM ARISING OUT OF OR RELATED TO A PARTY'S PERFORMANCE OF ITS OBLIGATIONS HEREUNDER, FOR ANY INCIDENTAL, PUNITIVE, SPECIAL, CONSEQUENTIAL OR OTHER INDIRECT DAMAGES, LOSS OF PROFITS, LOSS OF DATA OR USE OF DATA OR INTERRUPTION OF BUSINESS, EVEN IF SUCH PARTY OR ITS REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH LOSS. IN NO EVENT SHALL TOPCODER'S LIABILITY UNDER THIS AGREEMENT EXCEED THE FEES DUE OR PAYABLE UNDER THIS AGREEMENT FOR THE SERVICE GIVING RISE TO THE CLAIM.
6. CLAIMS OF INFRINGEMENT. If TopCoder becomes aware or reasonably believes that a Deliverable provided to you is or is likely to become, the subject of a claim of infringement, then TopCoder shall, at its option and expense either (i) procure for you the right to use the Deliverable or portion thereof, or (ii) replace or modify the Deliverable or portion thereof to make it non-infringing, or (iii) at TopCoder's option, accept the return of the Deliverable (or the portion thereof), and refund the undepreciated portion of the fees paid by you for that Deliverable, assuming a 12-month straight-line depreciation schedule. THIS SECTION 6 STATES THE ENTIRE LIABILITY OF TOPCODER WITH RESPECT TO INFRINGEMENT OF INTELLECTUAL PROPERTY RIGHTS RELATED TO THE DELIVERABLES, LICENSED CONTENT OR THEIR USE.
7. ARBITRATION OPTION. For any claim arising out of the services under this Agreement (excluding claims for injunctive or other equitable relief) where the total amount of the award sought is less than $10,000, the party requesting relief may elect to resolve the dispute in a cost effective manner through non-appearance-based arbitration. In the event a party elects arbitration, they shall initiate such arbitration through an established alternative dispute resolution ("ADR") provider mutually agreed upon by the parties (such agreement not to be unreasonably withheld). The ADR provider and the parties must comply with the following rules: (i) the arbitration shall be conducted by telephone, online and/or be solely based on written submissions, the specific manner shall be chosen by the party initiating the arbitration; (ii) the arbitration shall not involve any personal appearance by the parties or witnesses unless mutually agreed by the parties; and (iii) any judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. All claims brought against TopCoder must be resolved in accordance with this section. All claims filed or brought contrary to this section shall be considered improperly filed and may be dismissed for failure to abide by the procedures set forth herein.
8. PROMOTION. You agree to be identified as a customer of TopCoder and grant TopCoder permission to refer to you or Your company by name, tradename and/or trademark, if applicable, and to briefly describe Your business in TopCoder's marketing material, press releases and on its websites for the purpose of promoting Your relationship with TopCoder. The undersigned represents and warrants that s/he has the right to grant such permission, and that s/he is a duly authorized representative of and such company, and s/he is able to enter into and perform this Agreement.
9. GENERAL. This Agreement shall be governed in all respects by the laws of the State of Connecticut, USA without giving effect to principles of conflict of laws. The parties agree to submit to the jurisdiction of the Connecticut state and federal courts located in Hartford County, Connecticut for any claim relating to this Agreement which is not brought for arbitration pursuant to Section 7 above. The United Nations Convention for the International Sale of Goods shall not apply to this Agreement. All notices under this Agreement shall be in writing and shall be deemed to be made when delivered by overnight courier service to the Legal Department of such party at the address set forth on the first page of this Agreement, or to such other address as either party may specify by notice. If one party fails to enforce a provision of this Agreement, it shall not be precluded from enforcing the same provision at another time. If any provision of this Agreement is deemed unenforceable or invalid by law or by a court decision, the provision shall be changed and interpreted if possible to accomplish the intent of the provision within the constraints of the law. In the event the provision may not be so changed or interpreted, then only that provision, and not the entire agreement, shall be invalidated. Notwithstanding any provision to the contrary in this Agreement, if either party is prevented from complying, either totally or in part, with any of its obligations under this Agreement because of matters outside such party's reasonable control (i.e., a force majeure event), then upon written notice to the other party, such obligations will be suspended during the period of such disability. Nothing contained in this Agreement shall be construed as creating any agency, partnership, or other form of joint enterprise between the parties. You may not assign this Agreement in whole or in part without the prior written consent of TopCoder. Subject to the foregoing, this Agreement shall be binding on the parties and their permitted assigns. Each party represents to the other party that it has the full corporate right, power and authority to enter into this Agreement and perform its obligations hereunder; and that when executed and delivered, this Agreement will constitute its legal, valid and binding obligation enforceable against it in accordance with its terms.
</pre>
</p>
</div>
<!-- End .helpArea -->

<div>
	<br/><br/>
	 <a class="button4" style="text-align:center" class="TB_closeWindowButton" onclick="javascript:closeTBBox();"><strong>OK</strong></a>
	<br/><br/> 
</div>

<div class="popupFooter">
    <h2>1-866-TOPCODER or <a href="mailto:DirectAssist@TopCoder.com">DirectAssist@TopCoder.com</a></h2>

    <p>TopCoder is the world's largest competitive software development community with 232,058 developers<br/>
        representing over 200 countries.</p>

    <p><strong>Copyright ©2001-2010, TopCoder, Inc. All rights reserved</strong></p>
</div>
<!-- End #footer -->
