delete from screening_result
delete from screening_response_lu
delete from response_severity_lu
delete from screening_task
delete from screening_status_lu
delete from upload
delete from resource_info
delete from resource
delete from resource_info_type_lu
delete from project
delete from project_category_lu
