drop table studio_competition_change_history;
drop table software_competition_change_history;
drop table studio_competition_pipeline_resources;
drop table studio_competition_pipeline_info;
drop table software_competition_pipeline_info;