/*
 * Copyright (C) 2009 TopCoder Inc., All Rights Reserved.
 */
package com.topcoder.service.user;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * This class represents the "user_service_fault" element in WSDL. It's contained in the related exception-message
 * class. It was generated by JBoss tools and I changed the name and other little changes.
 * </p>
 * 
 * <p>
 * Updated for Jira and Confluence User Sync Widget 1.0
 *  - Correct few of JavaDoc comments.
 * </p>
 * 
 * <p>
 * This class is not thread safe because it's highly mutable
 * </p>
 * 
 * @author snow01
 * @since Cockpit Release Assembly for Receipts
 * @version 1.0
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "faultMessage" })
@XmlRootElement(name = "user_service_fault")
public class UserServiceFault implements Serializable {

    /**
     * Default serial version id.
     */
    private static final long serialVersionUID = 1L;

    /**
     * <p>
     * Represents the persistence message
     * </p>
     */
    @XmlElement(name = "faultString", required = true)
    private String faultMessage;

    /**
     * <p>
     * This is the default constructor. It does nothing.
     * </p>
     */
    public UserServiceFault() {
    }

    /**
     * <p>
     * Gets the value of the faultMessage property.
     * </p>
     * 
     * @return the value of the faultMessage property.
     */
    public String getFaultMessage() {
        return faultMessage;
    }

    /**
     * <p>
     * Sets the value of the persistenceMessage property.
     * </p>
     * 
     * @param faultMessage
     *            the value of the faultMessage property to set, can be null, can be empty
     */
    public void setFaultMessage(String faultMessage) {
        this.faultMessage = faultMessage;
    }
}
